# Generated by Django 3.1.1 on 2020-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataschema',
            options={'ordering': ['name'], 'verbose_name': 'Data schema', 'verbose_name_plural': 'Data schemas'},
        ),
        migrations.AlterField(
            model_name='column',
            name='range_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='range_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
