# Generated by Django 3.1.1 on 2020-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0002_auto_20200921_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['data_schema'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], max_length=100, verbose_name='Column separator'),
        ),
    ]
