# Generated by Django 3.1.1 on 2020-09-23 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0004_auto_20200922_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
