# Generated by Django 3.1.1 on 2020-09-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0005_dataschema_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_columns', to='fakecsv.dataschema'),
        ),
    ]
