# Generated by Django 3.1.1 on 2020-09-23 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0006_auto_20200923_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='DataSchemaColumn',
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='modified',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
