# Generated by Django 3.1.1 on 2020-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0007_auto_20200923_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSchemaColumn',
            new_name='Column',
        ),
    ]
