"""
Django settings.

Generated by 'django-admin startproject' using Django 3.1.
"""
import os  # noqa

from .base_conf import BaseConf


class LocalConf(BaseConf):
    """Local settings for project."""
    SECRET_KEY = "a@t75@=qw+m15bp$b=dvyc*rp--o9^b_$k&ru4e_42zd4vn1@l"
    DEBUG = True
    BaseConf.INSTALLED_APPS.append('debug_toolbar')

    MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    REDIS_HOST = "localhost"
    REDIS_PORT = "6379"
    CELERY_BROKER_URL = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
    CELERY_RESULT_BACKEND = 'django-db'
    INTERNAL_IPS = ['127.0.0.1', ]
    ACCEPT_CONTENT = ['json']
    TASK_SERIALIZER = 'json'
    AWS_ACCESS_KEY_ID = 'AKIAJQF76VYHGMSGKK4A'
    AWS_SECRET_ACCESS_KEY = 'aGvKXT7K5KjLjLvl0JPOwfW2pn6VZEbxA5PMu7IJ'
    AWS_STORAGE_BUCKET_NAME = 'fakecsvdev'
