"""
Django settings.

Generated by 'django-admin startproject' using Django 3.1.
"""
from .base_conf import BaseConf


class ProdConf(BaseConf):
    """Production settings for project."""

    import os

    DB_NAME = os.environ.get("DB_NAME")
    DB_USER = os.environ.get("DB_USER")
    DB_PASSWORD = os.environ.get("DB_PASSWORD")
    DB_HOST = os.environ.get("DB_HOST")

    SECRET_KEY = os.environ.get("SECRET_KEY")

    DEBUG = True

    ALLOWED_HOSTS = ["fakecsv1.herokuapp.com"]

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": "5432",
        }
    }

    import dj_database_url

    db = dj_database_url.config()
    DATABASES["default"].update(db)

    REDIS_HOST = os.environ.get("REDIS_HOST")
    REDIS_PORT = os.environ.get("REDIS_PORT")
    REDIS_USER = os.environ.get("REDIS_USER")
    REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
    CELERY_BROKER_URL = os.environ.get("BROKER_URL")
    CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
